version: '3.9'

services:
  postgres:
    image: postgres:14.2
    container_name: biletado-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z

  keycloak:
    depends_on:
      - postgres
    container_name: biletado-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    image: jboss/keycloak:16.1.1
    expose:
      - "8080"
    restart: unless-stopped
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json:Z

  frontend:
    container_name: biletado-frontend
    image: ${FRONTEND_IMAGE_REPOSITORY}:${FRONTEND_IMAGE_VERSION}
    expose:
      - "80"
    restart: unless-stopped
    volumes:
      - ./frontend/config.json:/usr/share/nginx/html/assets/config.json:Z

  backend:
    container_name: biletado-backend
    image: ${BACKEND_IMAGE_REPOSITORY}:${BACKEND_IMAGE_VERSION}
    environment:
      KEYCLOAK_HOST: "traefik/auth"
      KEYCLOAK_REALM: "biletado"
    expose:
      - "9000"
    restart: unless-stopped

  traefik:
    depends_on:
      - keycloak
      - frontend
      - backend
      - jaeger
    container_name: biletado-traefik
    image: traefik:2.6
    ports:
      - "8080:8080"
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:Z
      - ./traefik/traefik.conf.d/:/etc/traefik/traefik.conf.d/:Z
  jaeger:
    container_name: biletado-jaeger
    image: jaegertracing/all-in-one:1.32
    environment:
      QUERY_BASE_PATH: "/jaeger"
    expose:
      - "5778"
      - "6831/udp"
      - "16686"
