version: '3.9'

services:
  postgres:
    image: postgres
    container_name: biletado-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z

  keycloak:
    depends_on:
      - postgres
    container_name: biletado-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    image: jboss/keycloak
    expose:
      - "8080"
    restart: unless-stopped
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json:Z

  frontend:
    container_name: biletado-frontend
    image: registry.gitlab.com/biletado/frontend/angular
    expose:
      - "80"
    restart: unless-stopped

  backend:
    container_name: biletado-backend
    image: registry.gitlab.com/biletado/backend/go
    environment:
      KEYCLOAK_HOST: "keycloak:8080"
      KEYCLOAK_REALM: "biletado"
    expose:
      - "9000"
    restart: unless-stopped

  traefik:
    depends_on:
      - keycloak
      - frontend
      - backend
    container_name: biletado-traefik
    image: traefik
    ports:
      - "8080:8080"
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:Z
      - ./traefik/traefik.conf.d/:/etc/traefik/traefik.conf.d/:Z
