version: '3.9'

services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z

  keycloak:
    depends_on:
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    image: jboss/keycloak:${KEYCLOAK_IMAGE_VERSION}
    expose:
      - "8080"
    restart: unless-stopped
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json:Z

  frontend:
    image: ${FRONTEND_IMAGE_REPOSITORY}:${FRONTEND_IMAGE_VERSION}
    expose:
      - "80"
    restart: unless-stopped
    volumes:
      - ./frontend/config.json:/usr/share/nginx/html/assets/config.json:Z

  backend:
    image: ${BACKEND_IMAGE_REPOSITORY}:${BACKEND_IMAGE_VERSION}
    environment:
      KEYCLOAK_HOST: "traefik"
      KEYCLOAK_REALM: "biletado"
      JAEGER_TRACECONTEXTHEADERNAME: ${JAEGER_TRACECONTEXTHEADERNAME}
    expose:
      - "9000"
    restart: unless-stopped

  traefik:
    depends_on:
      - keycloak
      - frontend
      - backend
      - jaeger
    image: traefik:${TRAEFIK_IMAGE_VERSION}
    ports:
      - "8080:8080"
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:Z
      - ./traefik/traefik.conf.d/:/etc/traefik/traefik.conf.d/:Z
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_IMAGE_VERSION}
    environment:
      QUERY_BASE_PATH: "/jaeger"
      TRAEFIK_TRACING_JAEGER_TRACECONTEXTHEADERNAME: ${JAEGER_TRACECONTEXTHEADERNAME}
    expose:
      - "5778"
      - "6831/udp"
      - "16686"
