version: '3.9'

services:
  postgres:
    image: postgres
    container_name: biletado-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z

  keycloak:
    depends_on:
      - postgres
    container_name: biletado-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    image: jboss/keycloak
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json:Z
