http:
  routers:
    swagger-ui:
      entryPoints:
        - web
      rule: PathPrefix(`/swagger-ui`)
      service: swagger-ui
  services:
    swagger-ui:
      loadBalancer:
        servers:
          - url: http://swagger-ui:8080
